/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiCoingeckoRouteImport } from './routes/api/coingecko'
import { Route as ApiCopilotRouteImport } from './routes/api/copilot'
import { Route as ApiDexRouteImport } from './routes/api/dex'
import { Route as ApiInspectRouteImport } from './routes/api/inspect'
import { Route as ApiSalesRouteImport } from './routes/api/sales'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiArtworkAddressRouteImport } from './routes/api/artwork/$address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiVisitorsLeaveRouteImport } from './routes/api/visitors/leave'
import { Route as ApiVisitorsPingRouteImport } from './routes/api/visitors/ping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoingeckoRoute = ApiCoingeckoRouteImport.update({
  id: '/api/coingecko',
  path: '/api/coingecko',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDexRoute = ApiDexRouteImport.update({
  id: '/api/dex',
  path: '/api/dex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInspectRoute = ApiInspectRouteImport.update({
  id: '/api/inspect',
  path: '/api/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesRoute = ApiSalesRouteImport.update({
  id: '/api/sales',
  path: '/api/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtworkAddressRoute = ApiArtworkAddressRouteImport.update({
  id: '/api/artwork/$address',
  path: '/api/artwork/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitorsLeaveRoute = ApiVisitorsLeaveRouteImport.update({
  id: '/api/visitors/leave',
  path: '/api/visitors/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitorsPingRoute = ApiVisitorsPingRouteImport.update({
  id: '/api/visitors/ping',
  path: '/api/visitors/ping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/coingecko': typeof ApiCoingeckoRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/dex': typeof ApiDexRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/artwork/$address': typeof ApiArtworkAddressRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/visitors/leave': typeof ApiVisitorsLeaveRoute
  '/api/visitors/ping': typeof ApiVisitorsPingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/coingecko': typeof ApiCoingeckoRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/dex': typeof ApiDexRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/artwork/$address': typeof ApiArtworkAddressRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/visitors/leave': typeof ApiVisitorsLeaveRoute
  '/api/visitors/ping': typeof ApiVisitorsPingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/coingecko': typeof ApiCoingeckoRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/dex': typeof ApiDexRoute
  '/api/inspect': typeof ApiInspectRoute
  '/api/sales': typeof ApiSalesRoute
  '/api/search': typeof ApiSearchRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/artwork/$address': typeof ApiArtworkAddressRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/visitors/leave': typeof ApiVisitorsLeaveRoute
  '/api/visitors/ping': typeof ApiVisitorsPingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/coingecko'
    | '/api/copilot'
    | '/api/dex'
    | '/api/inspect'
    | '/api/sales'
    | '/api/search'
    | '/api/tokens'
    | '/api/artwork/$address'
    | '/api/auth/$'
    | '/api/visitors/leave'
    | '/api/visitors/ping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/coingecko'
    | '/api/copilot'
    | '/api/dex'
    | '/api/inspect'
    | '/api/sales'
    | '/api/search'
    | '/api/tokens'
    | '/api/artwork/$address'
    | '/api/auth/$'
    | '/api/visitors/leave'
    | '/api/visitors/ping'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/coingecko'
    | '/api/copilot'
    | '/api/dex'
    | '/api/inspect'
    | '/api/sales'
    | '/api/search'
    | '/api/tokens'
    | '/api/artwork/$address'
    | '/api/auth/$'
    | '/api/visitors/leave'
    | '/api/visitors/ping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiCoingeckoRoute: typeof ApiCoingeckoRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiDexRoute: typeof ApiDexRoute
  ApiInspectRoute: typeof ApiInspectRoute
  ApiSalesRoute: typeof ApiSalesRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiTokensRoute: typeof ApiTokensRoute
  ApiArtworkAddressRoute: typeof ApiArtworkAddressRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiVisitorsLeaveRoute: typeof ApiVisitorsLeaveRoute
  ApiVisitorsPingRoute: typeof ApiVisitorsPingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coingecko': {
      id: '/api/coingecko'
      path: '/api/coingecko'
      fullPath: '/api/coingecko'
      preLoaderRoute: typeof ApiCoingeckoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dex': {
      id: '/api/dex'
      path: '/api/dex'
      fullPath: '/api/dex'
      preLoaderRoute: typeof ApiDexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inspect': {
      id: '/api/inspect'
      path: '/api/inspect'
      fullPath: '/api/inspect'
      preLoaderRoute: typeof ApiInspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales': {
      id: '/api/sales'
      path: '/api/sales'
      fullPath: '/api/sales'
      preLoaderRoute: typeof ApiSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artwork/$address': {
      id: '/api/artwork/$address'
      path: '/api/artwork/$address'
      fullPath: '/api/artwork/$address'
      preLoaderRoute: typeof ApiArtworkAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitors/leave': {
      id: '/api/visitors/leave'
      path: '/api/visitors/leave'
      fullPath: '/api/visitors/leave'
      preLoaderRoute: typeof ApiVisitorsLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visitors/ping': {
      id: '/api/visitors/ping'
      path: '/api/visitors/ping'
      fullPath: '/api/visitors/ping'
      preLoaderRoute: typeof ApiVisitorsPingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiCoingeckoRoute: ApiCoingeckoRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiDexRoute: ApiDexRoute,
  ApiInspectRoute: ApiInspectRoute,
  ApiSalesRoute: ApiSalesRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiTokensRoute: ApiTokensRoute,
  ApiArtworkAddressRoute: ApiArtworkAddressRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiVisitorsLeaveRoute: ApiVisitorsLeaveRoute,
  ApiVisitorsPingRoute: ApiVisitorsPingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
